services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    volumes:
      - ./data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      - WEBUI_PORT=4444
      - PORT=4444
      - ENABLE_WEB_SEARCH=true
      - WEB_SEARCH_ENGINE=ddgs
    restart: unless-stopped